language: node_js
node_js:
  - "8.10"
install:
  - yarn install
before_deploy:
  - npm run build
deploy:
  provider: pages
  github-token: $GITHUB_TOKEN
  skip-cleanup: true
  local-dir: dist
  on:
    branch: master
