language: node_js
node_js:
  - "8.10"
script:
  - yarn lint
  - yarn ptfy
  - yarn test
install:
  - yarn install
before_deploy:
  - yarn build
deploy:
  provider: pages
  github-token: $GITHUB_TOKEN
  skip-cleanup: true
  local-dir: dist
  on:
    branch: master
